// Lets the owner add commands straight from WhatsApp — no GitHub, no redeploy.
// Custom commands are saved as plain .js files under ./custom, then required
// like any other module and registered into the live command map.
const fs = require('fs');
const path = require('path');

const CUSTOM_DIR = path.join(__dirname, 'custom');
if (!fs.existsSync(CUSTOM_DIR)) fs.mkdirSync(CUSTOM_DIR, { recursive: true });

function safeName(name) {
  return String(name || '').toLowerCase().replace(/[^a-z0-9_-]/g, '');
}

function pluginPath(name) {
  return path.join(CUSTOM_DIR, `${safeName(name)}.js`);
}

// Wraps a raw function body (what the owner typed after .addplugin <name>) into
// a full command module and writes it to disk.
function writePlugin({ name, aliases = [], category = 'CUSTOM', description = '', body }) {
  const clean = safeName(name);
  if (!clean) throw new Error('Invalid command name — use letters, numbers, - or _.');

  const fileContent = `// Auto-generated by .addplugin — ${new Date().toISOString()}
module.exports = {
  name: ${JSON.stringify(clean)},
  aliases: ${JSON.stringify(aliases)},
  category: ${JSON.stringify(category)},
  description: ${JSON.stringify(description)},
  async execute(ctx) {
    const { sock, msg, from, sender, args, text, isGroup, sessionId, quoted, prefix, command } = ctx;
${body}
  },
};
`;

  const filePath = pluginPath(clean);
  fs.writeFileSync(filePath, fileContent, 'utf8');
  return filePath;
}

// Saves a full ready-made module (e.g. a .js file the owner forwarded/attached)
// as-is — it must already export { name, execute }.
function writeFullModule(name, code) {
  const filePath = pluginPath(name);
  fs.writeFileSync(filePath, code, 'utf8');
  return filePath;
}

// require() (or re-require, for overwrites) a single plugin file and register it.
function loadPlugin(filePath, register) {
  const resolved = require.resolve(filePath);
  delete require.cache[resolved]; // allow hot-reload when a plugin is replaced
  const mod = require(resolved);
  if (!mod || !mod.name || typeof mod.execute !== 'function') {
    throw new Error('Plugin file must export { name, execute }.');
  }
  register(mod);
  return mod;
}

// Loads every .js file already saved under ./custom — call once at startup so
// plugins added via WhatsApp survive a bot restart.
function loadAllPlugins(register) {
  const files = fs.readdirSync(CUSTOM_DIR).filter((f) => f.endsWith('.js'));
  const loaded = [];
  for (const file of files) {
    try {
      const mod = loadPlugin(path.join(CUSTOM_DIR, file), register);
      loaded.push(mod.name);
    } catch (err) {
      console.error(`[pluginLoader] Failed to load ${file}:`, err.message);
    }
  }
  return loaded;
}

function removePlugin(name) {
  const filePath = pluginPath(name);
  if (!fs.existsSync(filePath)) return false;
  const resolved = require.resolve(filePath);
  delete require.cache[resolved];
  fs.unlinkSync(filePath);
  return true;
}

function listPlugins() {
  return fs.readdirSync(CUSTOM_DIR)
    .filter((f) => f.endsWith('.js'))
    .map((f) => f.replace(/\.js$/, ''));
}

module.exports = {
  writePlugin,
  writeFullModule,
  loadPlugin,
  loadAllPlugins,
  removePlugin,
  listPlugins,
  pluginPath,
  safeName,
  CUSTOM_DIR,
};
